### ISSUE TITLE
MemoryError after changing sampling frequency

### ISSUE THREAD

**Issue by IljaPilja** [Eden-Kramer-Lab/rate_adjustment_for_spike_coherence#1]
Hi,
I would like to use your code to determine the spike-field coherence of my data. My sampling rate is 20 kHz, I have 200 trials,  and I would like to examine a 300 ms time interval. I initially tried the example using the surrogate LFPs and spikes based on the Aoi et al., 2015 publication. This worked great. After I converted my spike data and LFP data into the correct format I ran it and I obtained a MemoryError. 
To try to determine what was causing the error I used the surrogate data example again and there I changed the n_time to 10000, the sampling_frequency to 10000 and ran the code. Again I obtained the same MemoryError:

> Connected to pydev debugger (build 202.8194.22)
INFO:spectral_connectivity.transforms:Multitaper(sampling_frequency=10000, time_halfbandwidth_product=5,
           time_window_duration=1.0, time_window_step=1.0,
           detrend_type='constant', start_time=0, n_tapers=9)
INFO:spectral_connectivity.transforms:Multitaper(sampling_frequency=10000, time_halfbandwidth_product=25,
           time_window_duration=1.0, time_window_step=1.0,
           detrend_type='constant', start_time=0, n_tapers=49)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/dsuchane/PycharmProjects/iCSD/Test_coherence.py", line 78, in <module>
    c = Connectivity.from_multitaper(m)
  File "C:\Users\dsuchane\PycharmProjects\untitled\venv\lib\site-packages\spectral_connectivity\connectivity.py", line 108, in from_multitaper
    fourier_coefficients=multitaper_instance.fft(),
  File "C:\Users\dsuchane\PycharmProjects\untitled\venv\lib\site-packages\spectral_connectivity\transforms.py", line 217, in fft
    self.sampling_frequency).swapaxes(2, -1)
  File "C:\Users\dsuchane\PycharmProjects\untitled\venv\lib\site-packages\spectral_connectivity\transforms.py", line 315, in _multitaper_fft
    tapers[np.newaxis, np.newaxis, ...])
MemoryError
python-BaseException
Backend TkAgg is interactive backend. Turning interactive mode on.

If I run only 20 trials at a time it works, so what I thought I'd do is run a set of 20 trials at a time and then average the 20 resulting coherence spectra. I'm not sure if that is even allowed, I'm not a mathematician. Any help on this would be greatly appreciated.

Thanks.

**Comment by edeno** [comment]
Hey,

So you're running out of memory, probably because of how highly sampled your data is. I would downsample your data to a more manageable sampling rate. For most things, if you downsample to 1000 Hz (for spikes and LFPs), that should still give you enough resolution to resolve frequencies up to 500 Hz.

**Comment by IljaPilja** [comment]
Hi,
so when I resample my 300 ms data piece (aka 6000 data ticks) at 20 kHz to 1 kHz, the LFP looks ok, but my binary vector containing ones for my spike times only consists of zeros since the resampling step has removed them all. Thus the coherence measurement does not work with spike vectors consisting of only zeros. Besides the factor of 20 downsampling I tried 10, 5, 2.5, the latter produces the MemoryError again and the others give me an almost flat coherence signal. Guess my data does not work with this function. Thanks for the quick response though.

**Comment by edeno** [comment]
There's nothing in downsampling that will remove your spike times.

For example if you spike times are 0.001, 0.005, 0.007 seconds and you had 1 ms bins (sampling rate: 500 Hz), you would have something like 1, 0, 0, 0, 1, 0, 1.

If you downsample to 2 ms bins (sampling rate: 1000 Hz), this would now be: 1, 0, 1, 1

**Comment by Mark-Kramer** [comment]
For the missing spike times, an option could be:

1. Get the spike times at high sampling frequency.
2. Downsample the LFP to 1 kHz. 
3. Make a vector of zeros, with sampling rate 1 kHz, and length equal to that of the LFP.
4. Put this spike times from (1) at the correct temporal locations in the vector in (3).

This would perhaps, preserve your spike times in (1), and let you downsample in (2).

**Comment by IljaPilja** [comment]
Thanks for the great help. I'm using the rebin package from Python to perform the downsampling and this works great with my data and I'm able to now determine the coherence.
Thank you again for your help.
